<a href="https://colab.research.google.com/github/Niharikaaasingh/MachineLearning/blob/main/Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import StackingClassifier

In [139]:
df = sns.load_dataset('iris')

In [140]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [141]:
x =  df.drop('species', axis=1)
y = df['species']

In [142]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [143]:
x_train,x_test,y_train,y_test = train_test_split(x,y_encoded,test_size=0.2,random_state=42, stratify=y_encoded)

In [144]:
base_learners = [
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('lr',LogisticRegression(max_iter = 1000)),
    ('svc',SVC(probability= True,kernel='rbf',random_state = 42))

]

In [145]:


meta_learner = LogisticRegression(max_iter = 1000)

In [146]:
stacking_clf = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv = 5
    )

In [147]:
stacking_clf.fit(x_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000)),
                               ('svc', SVC(probability=True, random_state=42))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [148]:
y_pred = stacking_clf.predict(x_test)

In [149]:
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9666666666666667

In [150]:
from sklearn.ensemble import RandomForestClassifier

In [151]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42
    )

In [152]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [153]:
y_pred = rf_model.predict(x_test)

In [154]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
38            4.4          3.0           1.3          0.2
127           6.1          3.0           4.9          1.8
57            4.9          2.4           3.3          1.0
93            5.0          2.3           3.3          1.0
42            4.4          3.2           1.3          0.2
56            6.3          3.3           4.7          1.6
22            4.6          3.6           1.0          0.2
20            5.4          3.4           1.7          0.2
147           6.5          3.0           5.2          2.0
84            5.4          3.0           4.5          1.5
107           7.3          2.9           6.3          1.8
141           6.9          3.1           5.1          2.3
104           6.5          3.0           5.8          2.2
51            6.4          3.2           4.5          1.5
7             5.0          3.4           1.5          0.2
49            5.0          3.3           1.4          0.2
14            5.8          4.0           1.2          0.2
69            5.6          2.5           3.9          1.1
63            6.1          2.9           4.7          1.4
138           6.0          3.0           4.8          1.8
10            5.4          3.7           1.5          0.2
140           6.7          3.1           5.6          2.4
58            6.6          2.9           4.6          1.3
134           6.1          2.6           5.6          1.4
132           6.4          2.8           5.6          2.2
77            6.7          3.0           5.0          1.7
75            6.6          3.0           4.4          1.4
18            5.7          3.8           1.7          0.3
116           6.5          3.0           5.5          1.8
28            5.2          3.4           1.4          0.2

In [155]:
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9

In [156]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [157]:
from xgboost import XGBClassifier

In [158]:
base_learners = [
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('lr',LogisticRegression(max_iter = 1000)),
    ('svc',SVC(probability= True,kernel='rbf',random_state = 42))

]

In [159]:
ada_model = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

In [160]:
ada_model.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [161]:
y_pred = ada_model.predict(x_test)

In [162]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
38            4.4          3.0           1.3          0.2
127           6.1          3.0           4.9          1.8
57            4.9          2.4           3.3          1.0
93            5.0          2.3           3.3          1.0
42            4.4          3.2           1.3          0.2
56            6.3          3.3           4.7          1.6
22            4.6          3.6           1.0          0.2
20            5.4          3.4           1.7          0.2
147           6.5          3.0           5.2          2.0
84            5.4          3.0           4.5          1.5
107           7.3          2.9           6.3          1.8
141           6.9          3.1           5.1          2.3
104           6.5          3.0           5.8          2.2
51            6.4          3.2           4.5          1.5
7             5.0          3.4           1.5          0.2
49            5.0          3.3           1.4          0.2
14            5.8          4.0           1.2          0.2
69            5.6          2.5           3.9          1.1
63            6.1          2.9           4.7          1.4
138           6.0          3.0           4.8          1.8
10            5.4          3.7           1.5          0.2
140           6.7          3.1           5.6          2.4
58            6.6          2.9           4.6          1.3
134           6.1          2.6           5.6          1.4
132           6.4          2.8           5.6          2.2
77            6.7          3.0           5.0          1.7
75            6.6          3.0           4.4          1.4
18            5.7          3.8           1.7          0.3
116           6.5          3.0           5.5          1.8
28            5.2          3.4           1.4          0.2

In [163]:
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9333333333333333

In [165]:
xgb_model= XGBClassifier(n_estimators=100,learning_rate = 0.1, max_depth = 3,
use_label_encoder = False ,eval_metric ='mlogloss',random_state=42)

In [166]:
xgb_model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [20:32:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [168]:
y_pred = xgb_model.predict(x_test)

In [169]:
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9333333333333333