<a href="https://colab.research.google.com/github/Niharikaaasingh/MachineLearning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [40]:
df = sns.load_dataset('iris')

In [41]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x = df.drop('species',axis = 1)
y = df['species']

In [45]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [49]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [50]:
model_knn.score(x_test,y_test)

1.0

In [51]:
from sklearn.svm import SVC

In [52]:
model_svm = SVC(gamma = 'auto')

In [53]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [54]:
model_svm.score(x_test,y_test)

1.0

now lets use grid search CV

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20, 30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [57]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [58]:
classifier.cv_results_

{'mean_fit_time': array([0.01917253, 0.0092175 , 0.01173701, 0.01491575, 0.01047106,
        0.01685343, 0.01469765, 0.00651875]),
 'std_fit_time': array([0.00592319, 0.00410658, 0.00330701, 0.00400059, 0.00265044,
        0.00627102, 0.00166155, 0.00244914]),
 'mean_score_time': array([0.0121769 , 0.00586171, 0.01125593, 0.00967326, 0.00686183,
        0.00843182, 0.01047993, 0.00521741]),
 'std_score_time': array([0.00159353, 0.0010768 , 0.00274829, 0.00302676, 0.00144549,
        0.00127649, 0.00287409, 0.00242108]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [59]:
results = pd.DataFrame(classifier.cv_results_)

In [60]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.019173,0.005923,0.012177,0.001594,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.009218,0.004107,0.005862,0.001077,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.011737,0.003307,0.011256,0.002748,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.014916,0.004001,0.009673,0.003027,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.010471,0.002650,0.006862,0.001445,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.016853,0.006271,0.008432,0.001276,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.014698,0.001662,0.010480,0.002874,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.006519,0.002449,0.005217,0.002421,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [61]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

using Randomized search CV

In [63]:
from sklearn.model_selection import RandomizedSearchCV

In [65]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20, 30],
    'kernel':['rbf','linear']
},n_iter = 4 , cv=5,return_train_score=False)

In [66]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [67]:
classifier_r.cv_results_

{'mean_fit_time': array([0.0043128 , 0.00410175, 0.00398936, 0.0060667 ]),
 'std_fit_time': array([5.20519915e-04, 3.33667053e-04, 8.76266093e-05, 2.03718988e-03]),
 'mean_score_time': array([0.00311613, 0.00354762, 0.00340056, 0.00565877]),
 'std_score_time': array([0.00017752, 0.00092932, 0.00080141, 0.00224815]),
 'param_kernel': masked_array(data=['linear', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 1, 30, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 30},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([1.        , 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.9       ]),
 'split3_test_score': array([0.9       , 0.96666667, 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.98      , 0.96      , 0.96666667]),
 'std_test_score': array([0.04898979, 0.01632993, 0.03887301, 0.0421637 ]),
 'rank_test_score': array([3, 1, 3, 2], dtype=int32)}

In [70]:
results_r = pd.DataFrame(classifier_r.cv_results_)

In [71]:
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004313,0.000521,0.003116,0.000178,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
1,0.004102,0.000334,0.003548,0.000929,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003989,0.000088,0.003401,0.000801,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
3,0.006067,0.002037,0.005659,0.002248,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,2

In [74]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1        1       linear         0.980000
2       30          rbf         0.960000
3       20       linear         0.966667

ENSEMBLE LEARNING